Feature/40835
sa11616079/javascript-client pull request #9
Opened 2020-12-17 05:44 UTC by sa11616079

1) Create a Trainee Component similar to other page component.
2) Inside Trainee Component create a folder named as components and create a new component AddDialog component
https://gyazo.com/3268e2b58ed78bd591db1ef3ce476c1a
3) AddDialog compoent will accept following props:
* open - boolean, will open the dialog if true.
* onClose - handler to close the dialog, passed from TraineeComponent
* onSubmit - handler to accept the dialog state for user: name, email, password
4) AddDialog will show information as show in the GIF
5) Add all the validations as shown in the GIF, similar to InputDemo component.
6) All the components used in the AddDialog must be from the Material UI.
7) TraineeComponent - Will hold the state of the Dialog, and update the state as per handler Request.
8) TraineeComponent - Will contain the button, and clicking on the button will open the dialog inside “AddDialog” component.

task ans : 
![a4](https://user-images.githubusercontent.com/72737801/102448816-f49a8880-4058-11eb-9aa4-d1f0bc123588.png)
![a3](https://user-images.githubusercontent.com/72737801/102448819-f5331f00-4058-11eb-89bf-2fc1b438f4f6.png)
![a2](https://user-images.githubusercontent.com/72737801/102448822-f5cbb580-4058-11eb-96fa-28b7bbd5b3f8.png)
![a1](https://user-images.githubusercontent.com/72737801/102448823-f5cbb580-4058-11eb-94a6-39fa24035f61.png)
![a5](https://user-images.githubusercontent.com/72737801/102448839-ffedb400-4058-11eb-98a6-ff9984c799fc.png)

: 
![a5](https://user-images.githubusercontent.com/72737801/102448810-f3695b80-4058-11eb-80aa-76d8d36b6ff2.png)

2020-12-17 14:02 UTC, SHUBHAM-JAIN-SS commented
please add the gif that is being mentioned here in the task description.

2020-12-17 14:18 UTC, sa11616079 commented
> please add the gif that is being mentioned here in the task description.

done sir

2020-12-23 14:22 UTC, SHUBHAM-JAIN-SS requested changes

2020-12-23 14:22 UTC, SHUBHAM-JAIN-SS commented on training/src/pages/Trainee/components/AddDialog/AddDialog.jsx
> +              onSubmit({
app breaking on clicking submit, please fix it, either don't call onSubmit or pass the definition of onSubmit from where you are using it.

2020-12-23 14:40 UTC, merged